version: '3.4'

services:
  flane-web-api-product:      
    image: flane-web-api-product:01-dev-linux
    build:
      target: develop
      context: .
      dockerfile: Flane.Web.Api.Product/dockerfile-linux
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # volumes:
    #   - FlaneWeb:/src
    volumes:
      - C:\Repositories\flane\app\Flane.Web:/src
    #stdin_open: true
    #tty: true
    entrypoint: dotnet watch run --verbose --no-launch-profile --configuration Debug
    ports:
      - "8000:80"
    depends_on:
      - sqldb   
  sqldb:
    image: flane-sql-db:01-dev-linux
    build:
      context: ./Flane.Sql.Db/
      dockerfile: dockerfile-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "flane2018"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S sqldb -U SA -P 'flane2018' -Q 'select 1'
    # networks:
    #   mynetwork:
    #     aliases:
    #       - db1.internal.prod.example.com



# networks:
#   default:
#     external:
#       name: nat

# volumes:
#   FlaneWeb:
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       #device: 'C:\Repositories\flane\app\Flane.Web'
#       device: '/c/Repositories/flane/app/Flane.Web'
