version: '3.4'

services:
  myapp-develop:
    image: myapp:dev
    build:
      target: develop
      context: .
      dockerfile: myapp\Dockerfile.develop
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - C:\Repositories\flane\prototypes\dockerplay\dockapp:C:\src
    entrypoint: dotnet watch -p myapp/ run --no-launch-profile
    ports:
      - "80"

networks:
  default:
    external:
      name: nat
