# escape=`
FROM mmercan/vs2017:15.7-10.0.14393.1715 as builder

WORKDIR C:\src\Common.Database
COPY Flane.Sql.Database\Flane.Database.Common .
RUN msbuild Flane.Database.Common.sqlproj

FROM microsoft/mssql-server-windows-developer:2016-sp1
ENV DATA_PATH="C:\data"
#     ACCEPT_EULA="Y" `
#     sa_password="DockerCon!!!"

VOLUME ${DATA_PATH}
WORKDIR C:\init

COPY Flane.Sql.Database\Initialize-Database.ps1 .
CMD powershell ./Initialize-Database.ps1 -sa_password $env:sa_password -data_path $env:data_path -Verbose

COPY --from=builder C:\src\Common.Database\bin\Debug\Flane.Database.Common.dacpac .