FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS develop
# RUN apt-get update && apt-get install bash
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Flane.Web.Api.Product
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Flane.Web.Api.Product/Flane.Web.Api.Product.csproj Flane.Web.Api.Product/
RUN dotnet restore Flane.Web.Api.Product/Flane.Web.Api.Product.csproj
COPY . .
WORKDIR /src/Flane.Web.Api.Product
RUN dotnet build Flane.Web.Api.Product.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Flane.Web.Api.Product.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Flane.Web.Api.Product.dll"]
