# escape=`
FROM sixeyed/msbuild:netfx-4.5.2-ssdt as builder

WORKDIR C:\src\Common.Database
COPY Flane.Sql.Database\Flane.Database.Common .
RUN msbuild Flane.Database.Common.sqlproj `
    /p:SQLDBExtensionsRefPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40" `
    /p:SqlServerRedistPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40"


FROM microsoft/mssql-server-windows-developer:2016-sp1

# ENV ACCEPT_EULA="Y" `
#     DATA_PATH="C:\data" `
#     sa_password="DockerCon!!!"

VOLUME ${DATA_PATH}
WORKDIR C:\init

COPY docker\db\Initialize-Database.ps1 .
CMD powershell ./Initialize-Database.ps1 -sa_password $env:sa_password -data_path $env:data_path -Verbose


COPY --from=builder C:\src\Common.Database\bin\Debug\Flane.Database.Common.dacpac .